# Part 2 of the IBM Capstone Project: Segmenting and Clustering Neighborhoods in Toronto

By Tobias Mehra

## Step 1: Get geo Data

In [1]:
# I tried using geocoder but it would not work so I am using the CSV file provided
import pandas as pd
# use pandas read function to convert file to dataframe
geo_data_df = pd.read_csv("https://cocl.us/Geospatial_data")
geo_data_df.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

## Import Toronto CSV file

In [2]:
# same as above with the csv file created in part 1 of this exercise

toronto_df = pd.read_csv("toronto_base.csv")
toronto_df.head()

   Unnamed: 0 Postal Code           Borough                    Neighbourhood
0           0         M3J        North York  Northwood Park, York University
1           1         M5C  Downtown Toronto                   St. James Town
2           2         M4L      East Toronto                     India Bazaar
3           3         M2M        North York          Newtonbrook, Willowdale
4           4         M1B       Scarborough                   Rouge, Malvern

## Merge the 2 files

In [4]:
# Merge two dataframes along the Postal Code using pandas merge function 

df_toronto_geo = pd.merge(toronto_df, geo_data_df, on="Postal Code")
df_toronto_geo.to_csv("toronto_geo.csv")
df_toronto_geo.head(10)

,Unnamed: 0,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,0,M3J,North York,"Northwood Park, York University",43.767980,-79.487262
1,1,M5C,Downtown Toronto,St. James Town,43.651494,-79.375418
2,2,M4L,East Toronto,India Bazaar,43.668999,-79.315572
3,3,M2M,North York,"Newtonbrook, Willowdale",43.789053,-79.408493
4,4,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
5,5,M3A,North York,Parkwoods,43.753259,-79.329656
6,6,M6L,North York,Maple Leaf Park,43.713756,-79.490074
7,7,M6P,West Toronto,High Park,43.661608,-79.464763
8,8,M6M,York,"Keelesdale, Mount Dennis, Silverthorn",43.691116,-79.476013
9,9,M6H,West Toronto,Dovercourt Village,43.669005,-79.442259

Thanks for reviewing!